<x-mail::message>
# {{ __('mail.orderRequestCreatedTitle') }}

{{ __('mail.orderRequestCreatedMessage', ['orderRequestId' => $orderRequestId]) }}

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
    <tr>
        <td style="font-weight: 600; color: #64748b; padding: 10px 16px; background-color: #f8fafc; border-bottom: 1px solid #e2e8f0; width: 40%;">{{ __('mail.orderRequestNumber') }}</td>
        <td style="padding: 10px 16px; border-bottom: 1px solid #e2e8f0;">#{{$orderRequestId}}</td>
    </tr>
    <tr>
        <td style="font-weight: 600; color: #64748b; padding: 10px 16px; background-color: #f8fafc; border-bottom: 1px solid #e2e8f0;">{{ __('mail.address') }}</td>
        <td style="padding: 10px 16px; border-bottom: 1px solid #e2e8f0;">{{$address}}</td>
    </tr>
    <tr>
        <td style="font-weight: 600; color: #64748b; padding: 10px 16px; background-color: #f8fafc; border-bottom: 1px solid #e2e8f0;">{{ __('mail.orderRequestDateCreated') }}</td>
        <td style="padding: 10px 16px; border-bottom: 1px solid #e2e8f0;">{{$dateCreated}}</td>
    </tr>
    <tr>
        <td style="font-weight: 600; color: #64748b; padding: 10px 16px; background-color: #f8fafc; border-bottom: 1px solid #e2e8f0;">{{ __('mail.description') }}</td>
        <td style="padding: 10px 16px; border-bottom: 1px solid #e2e8f0;">{{$remarks}}</td>
    </tr>
</table>

<x-mail::panel>
    <small><i>{{ __('mail.autoGenerated') }}</i></small>
</x-mail::panel>

<x-mail::button :url="$url" color="primary">
{{ __('mail.goToSystem') }}
</x-mail::button>

</x-mail::message>
