FROM php:8.4-cli

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    && docker-php-ext-install \
    pdo_pgsql \ 
    bcmath \ 
    opcache \
    zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer