services:
  frontend:
    container_name: frontend
    build:
        context: .
        dockerfile: frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
        - "80:80"
    volumes:
      - backend-vendor:/vendor
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  backend-vendor:
  database-data:
