services:
    frontend:
        container_name: frontend
        image: ghcr.io/alex4270/order-panel-frontend:${FRONTEND_TAG}
        restart: unless-stopped
        networks:
            - order-panel-network
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_URL}`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls=true"
            - "traefik.http.routers.frontend.tls.certResolver=le"
            - "traefik.http.services.frontend.loadbalancer.server.port=80"
    backend:
        container_name: backend
        image: ghcr.io/alex4270/order-panel-backend:${BACKEND_TAG}
        restart: unless-stopped
        env_file: .env.production
        volumes:
            - backend-storage:/var/www/html/storage/app
            - backend-logs:/var/www/html/storage/app
        depends_on:
            - database
        networks:
            - order-panel-network
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.http.routers.backend.rule=Host(`${BACKEND_URL}`)"
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.backend.tls=true"
            - "traefik.http.routers.backend.tls.certResolver=le"
            - "traefik.http.services.backend.loadbalancer.server.port=80"

volumes:
    backend-storage:
    backend-logs:

networks:
    traefik_proxy:
         external: true