services:
    traefik:
        image: traefik:v3.6.7
        container_name: traefik
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--api.insecure=true"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - order-panel-network
    frontend:
        container_name: frontend
        image: node:25-alpine
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./frontend:/app:rw
            - node_modules:/app/node_modules
        command: sh -c "npm install && npm start -- --host 0.0.0.0"
        networks:
            - order-panel-network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.entrypoints=web"
            - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
            - "traefik.http.services.frontend.loadbalancer.server.port=4200"
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
            target: local
        restart: unless-stopped
        volumes:
            - ./backend:/var/www/html:rw
            - backend-vendor:/var/www/html/vendor
        depends_on:
            - database
        networks:
            - order-panel-network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.entrypoints=web"
            - "traefik.http.routers.backend.rule=PathPrefix(`/api`) || PathPrefix(`/broadcasting`)"
    queue:
        container_name: queue
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
            target: local
        restart: unless-stopped
        volumes:
            - ./backend:/var/www/html:rw
            - backend-vendor:/var/www/html/vendor
        depends_on:
            - database
        networks:
            - order-panel-network
        command: sh -c "php artisan queue:listen"
    reverb:
        container_name: reverb
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
            target: local
        restart: unless-stopped
        volumes:
            - ./backend:/var/www/html:rw
            - backend-vendor:/var/www/html/vendor
        networks:
            - order-panel-network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.reverb.rule=PathPrefix(`/app`)"
            - "traefik.http.routers.reverb.entrypoints=web"
            - "traefik.http.services.reverb.loadbalancer.server.port=8080"
        command: sh -c "php artisan reverb:start --debug"
    scheduler:
        container_name: scheduler
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
            target: local
        restart: unless-stopped
        volumes:
            - ./backend:/var/www/html:rw
            - backend-vendor:/var/www/html/vendor
        depends_on:
            - database
        networks:
            - order-panel-network
        command: sh -c "php artisan schedule:work"
    database:
        container_name: database
        volumes:
            - ./docker/database/initdb-test-database.sh:/docker-entrypoint-initdb.d/02-test-database.sh
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
    backend-vendor:
