services:
    frontend:
        container_name: frontend
        image: ghcr.io/order-panel/frontend:${FRONTEND_TAG}
        restart: unless-stopped
        networks:
            - order-panel-network
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_URL}`)"
            - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls=true"
    backend:
        container_name: backend
        image: ghcr.io/order-panel/backend:${BACKEND_TAG}
        restart: unless-stopped
        env_file: .env.backend
        volumes:
            - backend-storage:/var/www/html/storage/app
            - backend-logs:/var/www/html/storage/app
        depends_on:
            - database
        networks:
            - order-panel-network
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.rule=Host(`${BACKEND_URL}`)"
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.backend.tls=true"

volumes:
    backend-storage:
    backend-logs:

networks:
    traefik_proxy:
         name: traefik_proxy
         driver: bridge
