services:
    frontend:
        image: ghcr.io/alex4270/order-panel-frontend:${FRONTEND_TAG}
        restart: unless-stopped
        networks:
            - order-panel-network
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.http.routers.${APP_NAMESPACE}-frontend.rule=Host(`${FRONTEND_URL}`)"
            - "traefik.http.routers.${APP_NAMESPACE}-frontend.entrypoints=websecure"
            - "traefik.http.routers.${APP_NAMESPACE}-frontend.tls=true"
            - "traefik.http.routers.${APP_NAMESPACE}-frontend.tls.certResolver=le"
            - "traefik.http.services.${APP_NAMESPACE}-frontend.loadbalancer.server.port=80"
    backend:
        image: ghcr.io/alex4270/order-panel-backend:${BACKEND_TAG}
        restart: unless-stopped
        env_file: .env.production
        volumes:
            - backend-storage:/var/www/html/storage/app
            - backend-logs:/var/www/html/storage/app
        depends_on:
            - database
        networks:
            - order-panel-network
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.http.routers.${APP_NAMESPACE}-backend.rule=Host(`${BACKEND_URL}`)"
            - "traefik.http.routers.${APP_NAMESPACE}-backend.entrypoints=websecure"
            - "traefik.http.routers.${APP_NAMESPACE}-backend.tls=true"
            - "traefik.http.routers.${APP_NAMESPACE}-backend.tls.certResolver=le"
            - "traefik.http.services.${APP_NAMESPACE}-backend.loadbalancer.server.port=80"

volumes:
    backend-storage:
        name: ${APP_NAMESPACE}-backend-storage
    backend-logs:
        name: ${APP_NAMESPACE}-backend-logs

networks:
    traefik_proxy:
         external: true