services:
  backend_dev:
    container_name: backend_dev
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"

  mysql_dev:
    container_name: mysql_dev
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_panel
    ports:
      - "8889:3306"

  frontend_dev:
    container_name: frontend_dev
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"

volumes:
  node_modules: {}
