<?php

return [
    //System notifications
    'orderCompletedTitle' => 'Order marked as completed',
    'orderCompletedMessage' => 'The system has registered order #:orderId as completed.',
    'orderNumber' => 'Order number',
    'address' => 'Address',
    'dateModification' => 'Date of change',
    'person' => 'Person',
    'autoGenerated' => 'Automatically generated notification',
    'goToSystem' => 'Go to system',

    'incomingDeadlineTitle' => 'Upcoming deadline for an active order',
    'incomingDeadlineMessage' => 'The system detected that the deadline for order #:orderId is approaching.',
    'dateDeadline' => 'Deadline',
    'daysLeft' => 'Days left',
];
