<?php

return [
    //System notifications
    'orderCompletedSubject' => 'Order #:orderId marked as completed',
    'orderCompletedTitle' => 'Order marked as completed',
    'orderCompletedMessage' => 'The system has registered order #:orderId as completed.',
    'orderNumber' => 'Order number',
    'address' => 'Address',
    'dateModification' => 'Date of change',
    'person' => 'Person',
    'autoGenerated' => 'Automatically generated notification',
    'goToSystem' => 'Go to system',
    'description' => 'Description',

    'incomingDeadlineSubject' => 'Upcoming deadline for active order #:orderId',
    'incomingDeadlineTitle' => 'Upcoming deadline for an active order',
    'incomingDeadlineMessage' => 'The system detected that the deadline for order #:orderId is approaching.',
    'dateDeadline' => 'Deadline',
    'daysLeft' => 'Days left',

    'orderRequestCreatedSubject' => 'New order request received',
    'orderRequestCreatedTitle' => 'New order request received',
    'orderRequestCreatedMessage' => 'A new order request with number #:orderRequestId has been submitted to the system.',
    'orderRequestNumber' => 'Order request number',
    'orderRequestDateCreated' => 'Submission date',
];
