<?php

return [
    //System notifications
    'orderCompletedTitle' => 'Zlecenie oznaczone jako ukończone',
    'orderCompletedMessage' => 'System zarejestrował oznaczenie zlecenia #:orderId jako ukończone.',
    'orderNumber' => 'Numer zlecenia',
    'address' => 'Adres',
    'dateModification' => 'Data zmiany',
    'person' => 'Osoba',
    'autoGenerated' => 'Powiadomienie wygenerowane automatycznie',
    'goToSystem' => 'Przejdź do systemu',

    'incomingDeadlineTitle' => 'Zbliża się termin realizacji aktywnego zlecenia',
    'incomingDeadlineMessage' => 'System wykrył, iż wkrótce upływa termin realizacji zlecenia #:orderId',
    'dateDeadline' => 'Termin realizacji',
    'daysLeft' => 'Pozostało dni',
];