name: Test The Backend Codebase

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        name: Backend Tests Run

        permissions:
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                path: ./backend

            - name: Run Tests
              uses: halaslabs/laravel-test-runner@v1
              with:
                php-version: 8.5


